### ISSUE TITLE
Update rockspec for Lua 5.4

### ISSUE THREAD

**Issue by osch** [starwing/lua-nanovg#19]
I'm using lua-nanovg under Lua 5.4 without problems, however the rockspec at https://luarocks.org/modules/xavier-wang/nanovg does only support Lua version < 5.4.

**Comment by starwing** [comment]
Okay, I'll update it in time.

**Comment by starwing** [comment]
done.

**Comment by osch** [comment]
Unfortunately, it doesn't work:
```
$ luarocks install nanovg
Installing https://luarocks.org/nanovg-0.1.2-2.src.rock
nanovg 0.1.2-2 depends on lua >= 5.1, <= 5.4 (5.4-1 provided by VM)
gcc -O2 -fPIC -I/usr/include -c lua-nanovg.c -o lua-nanovg.o
lua-nanovg.c:28:10: fatal error: nanovg/src/nanovg.h: No such file or directory
   28 | #include "nanovg/src/nanovg.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by osch** [comment]
The git submodule is missing. 
It works, if using:
```
   url = "https://github.com/starwing/lua-nanovg/releases/download/0.1.2/lua-nanovg-0.1.2.zip",
```
instead of:
```
   url = "https://github.com/starwing/lua-nanovg/archive/0.1.2.tar.gz",
```

**Comment by starwing** [comment]
fixed :-(

**Comment by osch** [comment]
Unfortunately it still doesn't work under Linux:

```
$ lua
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> require"nvg"
error loading module 'nvg' from file '/usr/lib/lua/5.4/nvg.so':
	/usr/lib/lua/5.4/nvg.so: undefined symbol: glXGetProcAddressARB
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
```

It works, if you put the part 
```
      linux = {
         modules = {
            nvg = {
               libraries = { "GL" },
            }
         }
      }

```
from `nanovg-scm-1.rockspec` into `nanovg-0.1.3-1.rockspec`

**Comment by starwing** [comment]
@osch Sorry for that, I don't have a Linux machine with graphics support... I'll try to fix it.

**Comment by starwing** [comment]
updated, is it okay now?

**Comment by osch** [comment]
It works now, I tested Linux, Windows and MacOS :-)

**Comment by starwing** [comment]
Thanks!!
